# Generated by Django 5.1.4 on 2025-01-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBGC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resized_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
